# Generated by Django 4.2.11 on 2026-02-11 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=78)),
                ('images', models.ImageField(blank=True, default='fallback.jpg', upload_to='pics/')),
                ('details', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=78)),
                ('price', models.PositiveIntegerField()),
                ('house_type', models.CharField(max_length=78)),
                ('bedroom', models.PositiveIntegerField()),
                ('bathroom', models.PositiveIntegerField()),
                ('toilet', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
