# Generated by Django 4.2.11 on 2026-03-01 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.CharField(max_length=225)),
                ('images', models.ImageField(blank=True, default='images/fallback.jpg', upload_to='images/')),
                ('location', models.CharField(max_length=78)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_package', models.CharField(max_length=78)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
