# Generated by Django 6.0.2 on 2026-02-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_estates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='banner',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, default='fallback.jpg', upload_to='pics'),
        ),
    ]
