# Generated by Django 4.2.11 on 2026-02-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatepost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
