# Generated by Django 4.2.11 on 2026-02-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_estates', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRecord',
        ),
    ]
